mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.TypeView.as_view(), name='type'),
    path('<type_name>/', views.MealsView.as_view(), name='meals'),
    path('<type_name>/<int:pk>/', views.IngredientsView.as_view(), name='ingredients'),
    path('<int:pk>/review/', views.ReviewView.as_view(), name='review'),
    path('<int:meals_id>/vote/', views.on_vote, name='on'),
]

mysite/polls/models.py
from django.db import models

#layout bazy danych z dodatkowymi danymi
#typ posilku 
class Type(models.Model):
    type_name = models.CharField(max_length=50) 
    def __str__(self):
        return self.type_name

#skladniki posilku 
class Ingredients(models.Model):
    ingredients_name = models.CharField(max_length=50)
    def __str__(self):
        return self.ingredients_name

#rodzaj posilku 
class Meals(models.Model):
    type = models.ForeignKey(Type, on_delete=models.CASCADE) #każdy meals związany z POJEDYNCZYM type
    meals_name = models.CharField(max_length=50)
    description = models.TextField(max_length=400)
    ingredients = models.ManyToManyField(Ingredients) #relacja z ingredients(opcje takie do wyboru)
    def __str__(self):
        return self.meals_name

#ocena przepisu 
class Review(models.Model):
    Meals = models.ForeignKey(Meals, on_delete=models.CASCADE)
    review = models.CharField(max_length=100)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.review

mysite/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.http import HttpResponse
from django.http import HttpResponseRedirect

from .models import Type, Meals, Review


class TypeView(generic.ListView):
    template_name = 'polls/type_list.html'
    context_object_name = 'type_list'
    def get_queryset(self):
        return Type.objects.all()


class MealsView(generic.ListView):
    template_name = 'polls/meals.html'
    context_object_name = 'meals_list'
    def get_queryset(self):
        return Meals.objects.filter(type__type_name=self.kwargs['type_name']).all()

class IngredientsView(generic.DetailView):
    model = Meals
    template_name = 'polls/ingredients.html'


class ReviewView(generic.DetailView):
    model = Meals
    template_name = 'polls/review.html'
    context_object_name = 'review'
    def get_queryset(self):
        return Meals.objects.filter(pk=self.kwargs['pk']).all()


def on_vote(request, meals_id):
    on = get_object_or_404(Meals, pk=meals_id)
    try:
        selected_choice = on.review_set.get(pk=request.POST['choice'])
    except (KeyError, Review.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/ingredients.html', {
            'meals': on,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:review', args=(on.id,)))

mysite/polls/templates/polls/ingredients.html
<html>
<body bgcolor="pink"; >
<style>
h1 {font-style: coursive;font-size: 50pt ; color:#eb00ac;}
h2 {font-size: 40pt;color:#8276df;}
h3 {font-size: 30pt;color:#000000;}
</style>
<legend><h1 style="text-align: center;"><strong>{{ meals.meals_name }}</strong></h1></legend>

<h2 style="text-align: left;"> Decsription:</span></h2>

<h3 style="text-align: left;"> {{ meals.description }}</span></h2>

<h2 style="text-align: left;"> Ingredients:</span></h2>

{% for ingredients in meals.ingredients.all %}
    <h3 style="text-align: left;"> {{ ingredients.ingredients_name }}</span></h3>
{% endfor %}

<h1 style="text-align: center;"> Opinions:</span></h1>

<form action="{% url 'polls:on' meals.id %}" method="post">
{% csrf_token %}

<fieldset>
    {% if error_message %}<h3 style="text-align: center;"><strong>{{ error_message }}</strong></h3>{% endif %}
    
    {% for choice in meals.review_set.all %}
        <h3><input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.review }}</label><br></h3>
    {% endfor %}
</fieldset>

    <h3 style="text-align: center;"><input type="submit" value="Rate"></h3>
    
</form>
</body>
</html>

mysite/polls/templates/polls/meals.html
<html>
<body bgcolor="#8276df";>
<style>
h1 {font-style: coursive;font-size: 50pt; color:#000000;  }
h2 {font-style: coursive;font-size: 40pt }
</style>

<legend><h1 style="text-align: center;"><strong>{{ meals_list.0.type }}</strong></h1></legend>

{% if meals_list %}
    <ul>
    {% for meals in meals_list %}
        <h2 style="text-align: center;"><a href="{% url 'polls:ingredients' meals.type meals.id%}"><span> #{{ meals.meals_name }}</span></a></h2>
    {% endfor %}
    </ul>
{% else %}
    <h2 style="text-align: center;">No meals are available.</h2>
{% endif %}

</body>
</html>

mysite/polls/templates/polls/review.html
<html>
<body bgcolor="#dea7e9";>
<style>
h1 {font-style: coursive; font-size: 50pt ;color:#25a48f;}
</style>

<h1 style="text-align: left;"><strong>Thank you for your review</strong></h1>

{% for review in result.review_set.all %}
        <li>{{ review.review }} -- {{ review.votes }} on_vote{{ review.votes|pluralize }}</li></h1>
{% endfor %}
</body>
</html>

mysite/polls/templates/polls/type_list.html
<html>
<body bgcolor="pink"; >
<style>
h1 {font-size: 64pt ; color:#000000;}
h2 {font-style: coursive;font-size: 50pt ; color:#eb00ac;}
h3 {font-size: 40pt;color:#8276df;}

</style>
<h1 style="text-align: center;"><b>The best recipes</b></h1>
<h2 style="text-align: center;"><i>Feel free to cook!</i></h2>
<h3 style="text-align: left;"><td>Our prepared dishes:</td></h1>

{% if type_list %} 
    <ul>
    {% for type in type_list %}
        <h2 style="text-align: left;"><a href="{% url 'polls:meals' type.type_name%}"><span> #{{ type.type_name }}</span></a></h2>
    {% endfor %}
    </ul>
{% else %}
    <h2 style="text-align: center;">No types are available.</h2>
{% endif %}

<img src="ksiazka.jpg">

</body>
</html>